include: package:flutter_lints/flutter.yaml

linter:
  rules:
    avoid_print: true
    prefer_single_quotes: false
analyzer:
  language:
    strict-inference: true
    strict-raw-types: true
  exclude:
    - android/**
    - test/**
    - oss-surveys-api/**
  errors:
    deprecated_member_use_from_same_package: warning
