name: Build APK
on: pull_request
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
        env:
          APP_UPDATES_BASE_URL: ${{ secrets.APP_UPDATES_BASE_URL }}
          MQTT_CLIENT_ID: ${{ secrets.MQTT_CLIENT_ID }}
          MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
          MQTT_PORT: ${{ secrets.MQTT_PORT }}
          MQTT_URL: ${{ secrets.MQTT_URL }}
          MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
          SURVEYS_API_BASE_PATH: ${{ secrets.SURVEYS_API_BASE_PATH }}
      - run: |
          touch .env
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build apk --split-per-abi

