name: Build APK
on:
  push:
    branches:
      - flutter-build
jobs:
  build:
    runs-on: ubuntu-latest
    environment: develop
    env:
      APP_UPDATES_BASE_URL: ${{ secrets.APP_UPDATES_BASE_URL }}
      MQTT_CLIENT_ID: ${{ secrets.MQTT_CLIENT_ID }}
      MQTT_PASSWORD: ${{ secrets.MQTT_PASSWORD }}
      MQTT_PORT: ${{ secrets.MQTT_PORT }}
      MQTT_URL: ${{ secrets.MQTT_URL }}
      MQTT_USERNAME: ${{ secrets.MQTT_USERNAME }}
      SURVEYS_API_BASE_PATH: ${{ secrets.SURVEYS_API_BASE_PATH }}
      SIGN_KEYSTORE: ${{ secrets.SIGN_KEYSTORE }}
      SIGN_STORE_PASSWORD: ${{ secrets.SIGN_STORE_PASSWORD }}
      SIGN_KEY_PASSWORD: ${{ secrets.SIGN_KEY_PASSWORD }}
      ENVIRONMENT: ${{ secrets.ENVIRONMENT }}
      FONT_URL: ${{ secrets.FONT_URL }}
      PLATFORM: ${{ secrets.PLATFORM }}
    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true
      - name: Build APK
        uses: subosito/flutter-action@v2
        with:
          flutter-version: "3.7.12"
          channel: "stable"
      - run: |
          echo $SIGN_KEYSTORE > /tmp/upload-keystore.b64 && base64 -d -i /tmp/upload-keystore.b64 > /tmp/upload-keystore.jks
          echo storePassword=$SIGN_STORE_PASSWORD >> android/key.properties
          echo keyPassword=$SIGN_KEY_PASSWORD >> android/key.properties
          echo keyAlias=upload >> android/key.properties
          echo storeFile=/tmp/upload-keystore.jks >> android/key.properties
          touch .env
          flutter pub get
          flutter pub run build_runner build --delete-conflicting-outputs
          flutter build apk --split-per-abi
      - name: Upload APK
        uses: shallwefootball/s3-upload-action@master
        with:
          aws_key_id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws_secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws_bucket: ${{ secrets.UPDATES_BUCKET }}
          source_dir: build/app/outputs/apk/release/
